# -*- coding: utf-8 -*-
"""Chương 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wF2mP6DbYjv2ns2EMIIZmb6tEfsE5lbx
"""

import os
import kagglehub
import pandas as pd
from PIL import Image

# 1. Tải tập dữ liệu từ Kaggle
path = kagglehub.dataset_download("anthonytherrien/dog-vs-cat")
print("Path to dataset files:", path)

# 2. Duyệt qua tất cả thư mục/tệp để lấy đường dẫn ảnh và nhãn
image_paths = []
labels = []

for root, dirs, files in os.walk(path):
    for file in files:
        if file.lower().endswith(('.jpg', '.jpeg', '.png')):
            full_path = os.path.join(root, file)
            image_paths.append(full_path)

            # Xác định nhãn dựa trên tên tệp hoặc tên thư mục chứa ảnh
            file_name = file.lower()
            if 'dog' in file_name or 'dog' in root.lower():
                labels.append('dog')
            elif 'cat' in file_name or 'cat' in root.lower():
                labels.append('cat')
            else:
                labels.append('unknown')

# 3. Tạo Pandas DataFrame để quản lý dữ liệu dễ dàng
df = pd.DataFrame({
    'image_path': image_paths,
    'label': labels
})

print(f"Tổng số ảnh tìm thấy: {len(df)}")
print(df.head())

# 4. Ví dụ: Mở và hiển thị ảnh đầu tiên bằng PIL (Pillow)
if not df.empty:
    sample_image_path = df.iloc[0]['image_path']
    sample_label = df.iloc[0]['label']

    img = Image.open(sample_image_path)
    print(f"\n[Ảnh mẫu] Nhãn: {sample_label} | Kích thước: {img.size}")
    # img.show() # Bỏ comment dòng này nếu muốn mở cửa sổ xem ảnh

import matplotlib.pyplot as plt
import tensorflow as tf
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

from tensorflow import keras
from keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation, Dropout, Flatten, Dense
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.utils import image_dataset_from_directory
from tensorflow.keras.preprocessing.image import ImageDataGenerator, load_img
from tensorflow.keras.preprocessing import image_dataset_from_directory

import os
import matplotlib.image as mpimg

import matplotlib.pyplot as plt
import matplotlib.image as mpimg

# Lấy 8 ảnh chó và 8 ảnh mèo từ DataFrame 'df' đã tạo ở ô [12]
dog_df = df[df['label'] == 'dog'].head(8)
cat_df = df[df['label'] == 'cat'].head(8)

# Gộp lại thành danh sách 16 ảnh
sample_df = pd.concat([cat_df, dog_df]).reset_index(drop=True)

fig = plt.gcf()
fig.set_size_inches(16, 16)

# Hiển thị 16 ảnh lên lưới 4x4
for i, row in sample_df.iterrows():
    sp = plt.subplot(4, 4, i + 1)
    sp.axis('Off')
    sp.set_title(row['label'], fontsize=12) # Hiển thị nhãn trên ảnh
    img = mpimg.imread(row['image_path'])
    plt.imshow(img)

plt.show()

# Sử dụng trực tiếp biến 'path' đã tải từ kagglehub ở ô [12]
base_dir = path

train_datagen = image_dataset_from_directory(
    base_dir,
    image_size=(200, 200),
    subset='training',
    seed=1,
    validation_split=0.1,
    batch_size=32
)

test_datagen = image_dataset_from_directory(
    base_dir,
    image_size=(200, 200),
    subset='validation',
    seed=1,
    validation_split=0.1,
    batch_size=32
)

model = tf.keras.models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(200, 200, 3)),
    layers.MaxPooling2D(2, 2),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D(2, 2),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D(2, 2),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D(2, 2),

    layers.Flatten(),
    layers.Dense(512, activation='relu'),
    layers.BatchNormalization(),
    layers.Dense(512, activation='relu'),
    layers.Dropout(0.1),
    layers.BatchNormalization(),
    layers.Dense(512, activation='relu'),
    layers.Dropout(0.2),
    layers.BatchNormalization(),
    layers.Dense(1, activation='sigmoid')
])

model.summary()

model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

history = model.fit(train_datagen,
          epochs=10,
          validation_data=test_datagen)