# -*- coding: utf-8 -*-
"""Bài 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kQ0SBfvp8tC8U6nQRwg10SL5wVJy4DI1
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Đọc dữ liệu từ tệp CSV
data = pd.read_csv('data_linear.csv').values
N = data.shape[0]
x = data[:, 0].reshape(-1, 1)
y = data[:, 1].reshape(-1, 1)

# Vẽ biểu đồ dữ liệu ban đầu
plt.scatter(x, y)
plt.xlabel('mét vuông')
plt.ylabel('giá')

# Chuẩn bị dữ liệu cho Linear Regression
x = np.hstack((np.ones((N, 1)), x))
w = np.array([0., 1.]).reshape(-1, 1)

numOfIteration = 100
cost = np.zeros((numOfIteration, 1))
learning_rate = 0.000001

for i in range(1, numOfIteration):
    r = np.dot(x, w) - y
    cost[i] = 0.5 * np.sum(r * r)
    w[0] -= learning_rate * np.sum(r)
    w[1] -= learning_rate * np.sum(np.multiply(r, x[:, 1].reshape(-1, 1)))
    print(cost[i])

# Dự đoán và vẽ đường tiệm cận
predict = np.dot(x, w)
plt.plot((x[0][1], x[N - 1][1]), (predict[0], predict[N - 1]), 'r')
plt.show()

# Dự đoán cho 50m2
x1 = 50
y1 = w[0] + w[1] * 50
print('Giá nhà cho 50m^2 là : ', y1)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Hàm sigmoid
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Load data từ file csv
data = pd.read_csv('data_linear.csv').values
N, d = data.shape

# Đọc dữ liệu 2 cột (1 cột x, 1 cột y)
x = data[:, 0:1].reshape(-1, 1)
y = data[:, 1].reshape(-1, 1)

# Vẽ data bằng scatter
x_cho_vay = x[y[:, 0] == 1]
x_tu_choi = x[y[:, 0] == 0]

plt.scatter(x_cho_vay[:, 0], np.zeros_like(x_cho_vay[:, 0]), c='red', s=30, label='cho vay')
plt.scatter(x_tu_choi[:, 0], np.zeros_like(x_tu_choi[:, 0]), c='blue', s=30, label='từ chối')
plt.legend(loc=1)
plt.xlabel('đặc trưng (x)')

# Thêm cột 1 vào dữ liệu x cho bias
x_b = np.hstack((np.ones((N, 1)), x))
w = np.array([0., 0.1]).reshape(-1, 1)

# Khởi tạo siêu tham số
numOfIteration = 1000
cost = np.zeros((numOfIteration, 1))
learning_rate = 0.01

for i in range(1, numOfIteration):
    # Tính giá trị dự đoán
    y_predict = sigmoid(np.dot(x_b, w))

    # Tính Loss (ép giá trị trong log để tránh lỗi log(0))
    y_predict_clipped = np.clip(y_predict, 1e-15, 1 - 1e-15)
    cost[i] = -np.sum(y * np.log(y_predict_clipped) + (1 - y) * np.log(1 - y_predict_clipped))

    # Gradient descent
    w = w - learning_rate * np.dot(x_b.T, y_predict - y)

print("Trọng số w sau khi huấn luyện:")
print(w)

#-*- coding: utf-8 -*-
"""
Created on Tue Mar  5 10:56:14 2019

@author: DELL
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Hàm sigmoid
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Toán tử AND
plt.scatter([1], [1], c='red', edgecolors='none', s=30, label='cho vay')
plt.scatter([0, 0, 1], [0, 1, 0], c='blue', edgecolors='none', s=30, label='từ chối')
plt.plot([0, 1.5], [1.5, 0], 'g')

# Toán tử OR
plt.scatter([0, 1, 1], [1, 0, 1], c='red', edgecolors='none', s=30, label='cho vay')
plt.scatter([0], [0], c='blue', edgecolors='none', s=30, label='từ chối')
plt.plot([-0.5, 1.5], [1, -1], 'g')
plt.xlabel('x1')
plt.ylabel('x2')

# Toán tử XOR
plt.scatter([1, 0], [0, 1], c='red', edgecolors='none', s=30, label='cho vay')
plt.scatter([1, 0], [1, 0], c='blue', edgecolors='none', s=30, label='từ chối')
plt.xlabel('x1')
plt.ylabel('x2')

# -*- coding: utf-8 -*-
import numpy as np
import pandas as pd

# Hàm sigmoid
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Đạo hàm hàm sigmoid
def sigmoid_derivative(x):
    return x * (1 - x)

# Lớp Neural Network
class NeuralNetwork:
    def __init__(self, layers, alpha=0.1):
        self.layers = layers
        self.alpha = alpha
        self.W = []
        self.b = []

        # Khởi tạo các tham số W, b ở mỗi layer
        for i in range(0, len(layers) - 1):
            w_ = np.random.randn(layers[i], layers[i + 1])
            b_ = np.zeros((layers[i + 1], 1))
            self.W.append(w_ / layers[i])
            self.b.append(b_)

    def __repr__(self):
        return "Neural network [{}]".format("-".join(str(l) for l in self.layers))

    def fit_partial(self, x, y):
        A = [x]

        # Quá trình feedforward
        out = A[-1]
        for i in range(0, len(self.layers) - 1):
            out = sigmoid(np.dot(out, self.W[i]) + (self.b[i].T))
            A.append(out)

        # Quá trình backpropagation
        y = y.reshape(-1, 1)

        # Ép giá trị A[-1] để tránh lỗi chia cho 0 hoặc log(0)
        A_last = np.clip(A[-1], 1e-15, 1 - 1e-15)
        dA = [-(y / A_last - (1 - y) / (1 - A_last))]

        dW = []
        db = []
        for i in reversed(range(0, len(self.layers) - 1)):
            dw_ = np.dot((A[i]).T, dA[-1] * sigmoid_derivative(A[i + 1]))
            db_ = (np.sum(dA[-1] * sigmoid_derivative(A[i + 1]), 0)).reshape(-1, 1)
            dA_ = np.dot(dA[-1] * sigmoid_derivative(A[i + 1]), self.W[i].T)
            dW.append(dw_)
            db.append(db_)
            dA.append(dA_)

        # Đảo ngược dW, db
        dW = dW[::-1]
        db = db[::-1]

        # Gradient descent
        for i in range(0, len(self.layers) - 1):
            self.W[i] = self.W[i] - self.alpha * dW[i]
            self.b[i] = self.b[i] - self.alpha * db[i]

    def fit(self, X, y, epochs=1000, verbose=100):
        for epoch in range(0, epochs):
            self.fit_partial(X, y)
            if epoch % verbose == 0:
                loss = self.calculate_loss(X, y)
                print("Epoch {}, loss {}".format(epoch, loss))

    def predict(self, X):
        for i in range(0, len(self.layers) - 1):
            X = sigmoid(np.dot(X, self.W[i]) + (self.b[i].T))
        return X

    def calculate_loss(self, X, y):
        y_predict = self.predict(X)
        y_predict_clipped = np.clip(y_predict, 1e-15, 1 - 1e-15)
        return -(np.sum(y * np.log(y_predict_clipped) + (1 - y) * np.log(1 - y_predict_clipped)))

# --- ĐỌC DỮ LIỆU VÀ HUẤN LUYỆN ---
# Đọc dữ liệu từ tệp data_linear.csv
data = pd.read_csv('data_linear.csv').values
N, d = data.shape

# Lấy cột đầu tiên làm X, cột thứ 2 làm y (vì data_linear.csv có 2 cột)
X = data[:, 0:1].reshape(-1, 1)
y = data[:, 1].reshape(-1, 1)

# Chuẩn hóa dữ liệu X để tránh bùng nổ gradient
X = (X - np.mean(X)) / np.std(X)

# Khởi tạo mô hình Neural Network: [1 đầu vào, 2 nút ẩn, 1 đầu ra]
p = NeuralNetwork([X.shape[1], 2, 1], alpha=0.01)
p.fit