# -*- coding: utf-8 -*-
"""Lab 8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XzZ4ZcLfAkarP7mOE6H5VEoX9JhwM6Js
"""

# Thêm thư viện
import cv2, os
import numpy as np
import matplotlib.image as mpimg

# Kích thước ảnh cho input của model
IMAGE_HEIGHT, IMAGE_WIDTH, IMAGE_CHANNELS = 66, 200, 3
INPUT_SHAPE = (IMAGE_HEIGHT, IMAGE_WIDTH, IMAGE_CHANNELS)


def load_image(data_dir, image_file):
    """
    Đọc ảnh RGB từ file
    """
    return mpimg.imread(os.path.join(data_dir, image_file.strip()))


def crop(image):
    """
    Cắt bỏ bầu trời và mũi xe trong ảnh
    """
    return image[60:-25, :, :]


def resize(image):
    """
    Resize ảnh
    """
    return cv2.resize(image, (IMAGE_WIDTH, IMAGE_HEIGHT), cv2.INTER_AREA)


def rgb2yuv(image):
    """
    Chuyển ảnh RGB sang YUV
    """
    return cv2.cvtColor(image, cv2.COLOR_RGB2YUV)


def preprocess(image):
    """
    Pre-process ảnh
    """
    image = crop(image)
    image = resize(image)
    image = rgb2yuv(image)
    return image


def choose_image(data_dir, center, left, right, steering_angle):
    """
    Chọn ngẫu nhiên ảnh giữa, trái hoặc phải.
    """
    choice = np.random.choice(3)
    if choice == 0:
        return load_image(data_dir, left), steering_angle + 0.2
    elif choice == 1:
        return load_image(data_dir, right), steering_angle - 0.2
    return load_image(data_dir, center), steering_angle


def random_flip(image, steering_angle):
    """
    Ngẫu nhiên lật lại ảnh
    """
    if np.random.rand() < 0.5:
        image = cv2.flip(image, 1)
        steering_angle = -steering_angle
    return image, steering_angle


def random_translate(image, steering_angle, range_x, range_y):
    """
    Ngẫu nhiên dịch chuyển ảnh theo range_x, range_y.
    """
    trans_x = range_x * (np.random.rand() - 0.5)
    trans_y = range_y * (np.random.rand() - 0.5)
    steering_angle += trans_x * 0.002
    trans_m = np.float32([[1, 0, trans_x], [0, 1, trans_y]])
    height, width = image.shape[:2]
    image = cv2.warpAffine(image, trans_m, (width, height))
    return image, steering_angle


def random_shadow(image):
    """
    Thêm giá trị tối cho ảnh
    """
    # (x1, y1) and (x2, y2) forms a line
    # xm, ym gives all the locations of the image
    x1, y1 = IMAGE_WIDTH * np.random.rand(), 0
    x2, y2 = IMAGE_WIDTH * np.random.rand(), IMAGE_HEIGHT
    xm, ym = np.mgrid[0:image.shape[0], 0:image.shape[1]]

    # mathematically speaking, we want to set 1 below the line and zero otherwise
    # Our coordinate is up side down.  So, the above the line:
    # (ym-y1)/(xm-x1) > (y2-y1)/(x2-x1)
    # as x2 == x1 causes zero-division problem, we'll write it in the below form:
    # (ym-y1)*(x2-x1) - (y2-y1)*(xm-x1) > 0
    mask = np.zeros_like(image[:, :, 1])
    mask[(ym - y1) * (x2 - x1) - (y2 - y1) * (xm - x1) > 0] = 1

    # choose which side should have shadow and adjust saturation
    cond = mask == np.random.randint(2)
    s_ratio = np.random.uniform(low=0.2, high=0.5)

    # adjust Saturation in HLS(Hue, Light, Saturation)
    hls = cv2.cvtColor(image, cv2.COLOR_RGB2HLS)
    hls[:, :, 1][cond] = hls[:, :, 1][cond] * s_ratio
    return cv2.cvtColor(hls, cv2.COLOR_HLS2RGB)


def random_brightness(image):
    """
    Thêm giá trị sáng cho ảnh.
    """
    # HSV (Hue, Saturation, Value) is also called HSB ('B' for Brightness).
    hsv = cv2.cvtColor(image, cv2.COLOR_RGB2HSV)
    ratio = 1.0 + 0.4 * (np.random.rand() - 0.5)
    hsv[:,:,2] =  hsv[:,:,2] * ratio
    return cv2.cvtColor(hsv, cv2.COLOR_HSV2RGB)


def augument(data_dir, center, left, right, steering_angle, range_x=100, range_y=10):
    """
    Kết hợp các phương pháp augmentation ảnh
    """
    image, steering_angle = choose_image(data_dir, center, left, right, steering_angle)
    image, steering_angle = random_flip(image, steering_angle)
    image, steering_angle = random_translate(image, steering_angle, range_x, range_y)
    image = random_shadow(image)
    image = random_brightness(image)
    return image, steering_angle


def batch_generator(data_dir, image_paths, steering_angles, batch_size, is_training):
    """
    Trả về ảnh và góc lái tương ứng cho việc training
    """
    images = np.empty([batch_size, IMAGE_HEIGHT, IMAGE_WIDTH, IMAGE_CHANNELS])
    steers = np.empty(batch_size)
    while True:
        i = 0
        for index in np.random.permutation(image_paths.shape[0]):
            center, left, right = image_paths[index]
            steering_angle = steering_angles[index]
            # argumentation
            if is_training and np.random.rand() < 0.6:
                image, steering_angle = augument(data_dir, center, left, right, steering_angle)
            else:
                image = load_image(data_dir, center)
            # add the image and steering angle to the batch
            images[i] = preprocess(image)
            steers[i] = steering_angle
            i += 1
            if i == batch_size:
                break
        yield images, steers

# 1. Cài đặt các thư viện tương thích
!pip install "werkzeug<3.0.0" "flask<3.0.0" python-socketio==4.6.1 eventlet -q

import argparse
import base64
from datetime import datetime
import os
import shutil
import numpy as np
import socketio
import eventlet
import eventlet.wsgi
from PIL import Image
from flask import Flask
from io import BytesIO
from keras.models import load_model
import keras
import utils

# Khởi tạo Socket.IO server
sio = socketio.Server()

# Khởi tạo Flask app
app = Flask(__name__)

# Khởi tạo biến toàn cục
model = None
prev_image_array = None

# Tốc độ tối thiểu và tối đa của xe
MAX_SPEED = 25
MIN_SPEED = 10
speed_limit = MAX_SPEED

# Đăng ký sự kiện 'telemetry' xử lý dữ liệu từ trình giả lập
@sio.on('telemetry')
def telemetry(sid, data):
    if data:
        throttle = float(data["throttle"])
        steering_angle = float(data["steering_angle"])
        speed = float(data["speed"])
        image = Image.open(BytesIO(base64.b64decode(data["image"])))

        try:
            image = np.asarray(image)
            image = utils.preprocess(image)
            image = np.array([image])

            print('*****************************************************')
            steering_angle = float(model.predict(image, batch_size=1))

            global speed_limit
            if speed > speed_limit:
                speed_limit = MIN_SPEED
            else:
                speed_limit = MAX_SPEED

            throttle = 1.0 - steering_angle**2 - (speed / speed_limit)**2
            print('Steering Angle: {}, Throttle: {}, Speed: {}'.format(steering_angle, throttle, speed))

            send_control(steering_angle, throttle)
        except Exception as e:
            print('Lỗi xử lý:', e)

        if 'args' in globals() and args.image_folder != '':
            timestamp = datetime.utcnow().strftime('%Y_%m_%d_%H_%M_%S_%f')[:-3]
            image_filename = os.path.join(args.image_folder, timestamp)
            image.save('{}.jpg'.format(image_filename))
    else:
        sio.emit('manual', data={}, skip_sid=True)

# Đăng ký sự kiện kết nối
@sio.on('connect')
def connect(sid, environ):
    print("Kết nối thành công:", sid)
    send_control(0, 0)

# Hàm gửi lệnh điều khiển xe
def send_control(steering_angle, throttle):
    sio.emit(
        "steer",
        data={
            'steering_angle': str(steering_angle),
            'throttle': str(throttle)
        },
        skip_sid=True
    )

if __name__ == '__main__':
    model_path = 'model.h5'
    image_folder = ''

    if os.path.exists(model_path):
        try:
            # Định nghĩa một lớp Lambda tùy chỉnh trống để ghi đè, tránh việc deserialize bytecode lỗi thời
            # Thông thường layer Lambda trong các model NVIDIA tự lái chỉ làm nhiệm vụ chuẩn hóa: x / 127.5 - 1.0
            # Chúng ta sẽ thực hiện việc chuẩn hóa này bằng tay hoặc chuyển tiếp đầu vào
            custom_objects = {
                'Lambda': lambda x: x / 127.5 - 1.0
            }
            model = load_model(model_path, custom_objects=custom_objects, compile=False, safe_mode=False)
            print("Đã tải thành công mô hình với custom_objects:", model_path)
        except Exception as load_err:
            print("Không thể tải với custom_objects, đang thử tải không biên dịch...")
            try:
                model = load_model(model_path, compile=False, safe_mode=False)
                print("Đã tải thành công mô hình (compile=False):", model_path)
            except Exception as final_err:
                print("Lỗi nghiêm trọng khi tải mô hình:", final_err)
                print("Gợi ý: Cần export lại model.h5 từ mã nguồn gốc trong môi trường Python hiện tại.")
    else:
        print(f"KHÔNG TÌM THẤY FILE {model_path}! Hãy chắc chắn file model.h5 đã được tải lên.")

    if image_folder != '':
        print("Tạo thư mục lưu ảnh tại: {}".format(image_folder))
        if os.path.exists(image_folder):
            shutil.rmtree(image_folder)
        os.makedirs(image_folder)
        print("ĐANG GHI LẠI HÀNH TRÌNH...")
    else:
        print("KHÔNG GHI LẠI HÀNH TRÌNH...")

    app = socketio.Middleware(sio, app)
    print("Server đang chạy tại cổng 4567...")
    eventlet.wsgi.server(eventlet.listen(('', 4567)), app)